name: Build and Deploy Clariolane to Server
  
on:
  push:
    branches: ["deploy_test"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Inject environment variables
        run: |
          export VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
          export VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          export VITE_PAYSTACK_PUBLIC_KEY=${{ secrets.VITE_PAYSTACK_PUBLIC_KEY }}

      - name: Build The App
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH 
        uses: appleboy/ssh-action@v1.0.3 # Use a reliable SSH action
        with:
          host: ${{ secrets.SERVER_HOST }}      # e.g., your_server_ip
          key: ${{ secrets.SERVER_SSH_KEY }}    # The private SSH key of the user
          username: ${{ secrets.SERVER_USER }}  # e.g., ubuntu or root
          
          script: |
            echo "Deploying the project..."
            TEMP_DIR=/var/www
            scp -r ./dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:$TEMP_DIR/
            # cd /var/www && sudo mkdir hello
            echo 'Build was successful to digital ocean'

      # - name: Deploy to Ubuntu Server via SSH
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       # sudo tcpdump -i any port 22
      #       echo: ${{ secrets.SERVER_USER }}

      #       Variables
      #       APP_DIR=/var/www/html
      #       TEMP_DIR=/var/www/html-new

      #       # mkdir -p $APP_DIR

      #       # # Remove previous temp dir if exists
      #       # rm -rf $TEMP_DIR

      #       # # Copy new build
      #       # mkdir -p $TEMP_DIR
      #       # scp -r ./dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:$TEMP_DIR/

      #       # # Swap directories for zero-downtime
      #       # mv $APP_DIR $APP_DIR-old || true
      #       # mv $TEMP_DIR $APP_DIR
      #       # rm -rf $APP_DIR-old

      #       # # Reload nginx to ensure any cache cleared
      #       # sudo systemctl reload nginx

# deploy: # Works
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install doctl # Works
  #       uses: jjst/action-digitalocean-deploy-app@v2
  #       with:
  #         token: ${{ secrets.DO_PAT }}

  #     - name: Provision Droplet and deploy container
  #       run: doctl compute droplet create test --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
